version: "3.9"
services:
  mysql:
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_NAME:-tttdb}
      OpenRail__NR_USERNAME: ${NR_USERNAME:-jacX808}
      OpenRail__NR_PASSWORD: ${NR_PASSWORD:-pass}
      TZ: Europe/London
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
        
volumes:
  mysqldb:
