services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app}
      POSTGRES_DB: ${DB_NAME:-ttt}
    ports: ["3306:3306"]
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
