version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USERNAME:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app}
      POSTGRES_DB: ${DB_NAME:-ttt}
      OpenRail__NR_USERNAME: ${NR_USERNAME:-user}
      OpenRail__NR_PASSWORD: ${NR_PASSWORD:-pass}
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
