version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: tttMySQL
    environment:
      MYSQL_ROOT_PASSWORD: "dB@min5211"
      MYSQL_DATABASE: "ttt"
      MYSQL_HOST: "127.0.0.1"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    
  mysqlTest:
    image: mysql:8.4
    container_name: tttMySQLTest
    environment:
      MYSQL_ROOT_PASSWORD: "dB@min5211"
      MYSQL_DATABASE: "tttTest"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_USER: "testAdmin"
      MYSQL_PASSWORD: "test"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
  mysql_data_test: