version: "3.9"
services:
  ttt_container:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: "ttt"
      MYSQL_ROOT_PASSWORD: "dB@min5211"
      TZ: Europe/London
    ports:
      - "3306:3306"
    volumes:
      - ttt_container:/var/lib/mysql
        
volumes:
  ttt_container:
